GET http://localhost:8000/users HTTP/1.1

###

POST http://localhost:8000/users HTTP/1.1
content-type: application/json

{
    "name": "Juan Pérez",
    "email": "juan@sanchez.ct"
}


###

PUT http://localhost:8000/users HTTP/1.1
content-type: application/json

{
    "name": "Juan Alvarez",
    "email": "juan@perez.ct"
}

###

DELETE  http://localhost:8000/users HTTP/1.1
content-type: application/json

{
    "name": "Juan Pérez",
    "email": "juan@perez.ct"
}
